# Generated by Django 4.2.4 on 2024-06-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
