# Generated by Django 4.2.4 on 2024-06-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_logo',
            field=models.CharField(default='https://i.pinimg.com/736x/72/8b/6c/728b6c0d58d7e6b29e91faf8a1a31bc4.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_target_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trancheinvestor',
            name='invest_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
