# Generated by Django 4.2.4 on 2024-06-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryofbusiness',
            name='nature_of_business',
        ),
        migrations.AddField(
            model_name='natureofbusiness',
            name='category_of_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sfd.categoryofbusiness'),
        ),
        migrations.AlterField(
            model_name='tranchereport',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sfd.campaign'),
        ),
    ]
