# Generated by Django 4.2.4 on 2024-06-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0002_campaign_campaign_logo_campaign_min_target_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
