# Generated by Django 4.2.4 on 2024-06-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0002_remove_categoryofbusiness_nature_of_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='natureofbusiness',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
