# Generated by Django 4.2.4 on 2024-06-24 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0005_trancheentreprenuer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trancheentreprenuer',
            name='company',
        ),
    ]
