# Generated by Django 4.2.4 on 2024-06-24 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sfd', '0006_remove_trancheentreprenuer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='users.userprofile'),
        ),
    ]
