# Generated by Django 4.2.4 on 2024-06-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0006_companyprofile_category_of_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='natureofbusiness',
            name='category_of_business',
        ),
        migrations.AddField(
            model_name='categoryofbusiness',
            name='nature_of_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sfd.natureofbusiness'),
        ),
    ]
