# Generated by Django 4.2.4 on 2024-06-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0007_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranchereport',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
