# Generated by Django 4.2.4 on 2024-06-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0008_tranchereport_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranchereport',
            old_name='name',
            new_name='quarter',
        ),
        migrations.AddField(
            model_name='tranchereport',
            name='filename',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
