# Generated by Django 4.2.4 on 2024-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfd', '0009_rename_name_tranchereport_quarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranchereport',
            name='report',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
